# Generated by Django 5.2 on 2025-04-24 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster_det', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmaster_det.espacios', verbose_name='Espacio')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['id'],
            },
        ),
    ]
