# Generated by Django 5.2 on 2025-04-24 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster_det', '0002_estados'),
    ]

    operations = [
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=50, verbose_name='Tarea')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmaster_det.espacios', verbose_name='Espacio')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmaster_det.estados', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50, verbose_name='Detalle')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmaster_det.tareas', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'ordering': ['id'],
            },
        ),
    ]
