# Generated by Django 5.2 on 2025-04-24 22:13

import taskmaster_det.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster_det', '0003_tareas_detalles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalles',
            name='detalle',
        ),
        migrations.AddField(
            model_name='detalles',
            name='categoría',
            field=models.CharField(blank=True, max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='detalles',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='detalles',
            name='fecha_vencimiento',
            field=models.DateField(default=taskmaster_det.models.default_fecha_vencimiento),
        ),
        migrations.AddField(
            model_name='detalles',
            name='prioridad',
            field=models.IntegerField(default=1, verbose_name='Prioridad'),
        ),
    ]
