# Generated by Django 5.2 on 2025-04-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster_det', '0004_remove_detalles_detalle_detalles_categoría_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacios',
            name='usuario',
            field=models.CharField(default='usuario_por_defecto', max_length=50, verbose_name='Usuario'),
        ),
    ]
