# Generated by Django 5.2 on 2025-05-01 06:37

import taskmaster_det.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster_det', '0005_espacios_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='categoría',
            field=models.CharField(blank=True, max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='tareas',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='tareas',
            name='fecha_vencimiento',
            field=models.DateField(default=taskmaster_det.models.default_fecha_vencimiento),
        ),
        migrations.AddField(
            model_name='tareas',
            name='prioridad',
            field=models.IntegerField(default=1, verbose_name='Prioridad'),
        ),
        migrations.DeleteModel(
            name='detalles',
        ),
    ]
